### ISSUE TITLE
Web interface auto refresh causes bareos-dir unix socket leak

### ISSUE THREAD

**Issue by dknight-bg** [bareos/bareos#1797] opened 2024-04-30 14:41 UTC
### Bareos component version

bareos-fd --version  23.0.3~pre104.aaf825630
bareos-sd --version  23.0.3~pre104.aaf825630
bareos-dir --version  23.0.3~pre104.aaf825630 

bareos-webui-23.0.3~pre104.aaf825630-84.el9.x86_64

### Steps to reproduce

1. Open web interface - dashboard
2.  Wait  and monitor director open unix sockets (  lsof -p PID_OF_DIR   | grep 'type=STREAM' | wc -l )
3. Director does not respond after reaching the limit of open files

Unix sockets are connected to sssd_nss

### Expected results

director should close the sockets

### Actual results

Director does not respond after reaching the limit of open files

### Environment

```markdown
- OS: AlmaLinux 9.3
- component: 
sssd_nss 2.9.1-4.el9_3.5.alma.1.x86_64
```

### Relevant log output

```shell
lsof -p 259213   | grep 'type=STREAM'

bareos-di 259213 bareos    1u  unix 0xffff9d5d51d3bb80      0t0 3559130657 type=STREAM (CONNECTED)
bareos-di 259213 bareos    2u  unix 0xffff9d5d51d3bb80      0t0 3559130657 type=STREAM (CONNECTED)
bareos-di 259213 bareos    4u  unix 0xffff9d5d51d39100      0t0 3559130664 type=STREAM (CONNECTED)
................................................
bareos-di 259213 bareos  104u  unix 0xffff9d5d85d82200      0t0 3559148864 type=STREAM (CONNECTED)
bareos-di 259213 bareos  105u  unix 0xffff9d5d6dbf5500      0t0 3559147395 type=STREAM (CONNECTED)
bareos-di 259213 bareos  106u  unix 0xffff9d5d6dbf0440      0t0 3559147397 type=STREAM (CONNECTED)

lsof -p 259213   | grep 'type=STREAM' | wc -l
104
```

**Comment by arogge** [comment] 2024-05-02 07:27
Could you please elaborate on your PAM and NSS configuration a bit more?
Bareos itself doesn't talk to sssd or sssd_nss ever. I guess there's something going wrong when we indirectly access it via nss.

Also, could you (without using the Web UI) see if this still happens if you connect with a `bconsole` and at least check how many new stale sockets each new console connection will create? Maybe that only happens for PAM users (if you have any), but not the default console?

**Comment by dknight-bg** [comment] 2024-05-07 09:27
Hello,

I checked bconsole , does not create stale sockets at all .

/etc/nsswitch.conf :
passwd:     sss files systemd
shadow:     sss files
group:      sss files systemd


I dumped the result from strace of the processes.
( sudo strace -ff -s 1000 -p 1009190  --output /tmp/xxxx )

Result for one of the forked processes:
................
```
read(8, "\0\0\0\22", 4)                 = 4
read(8, ".api 2 compact=yes", 18)       = 18
write(8, "\377\377\377\361", 4)         = 4
write(8, "\0\0\0.{\"jsonrpc\":\"2.0\",\"id\":null,\"result\":{\"api\":2}}", 50) = 50
write(8, "\377\377\377\357", 4)         = 4
write(8, "\377\377\377\356", 4)         = 4
read(8, "\0\0\0005", 4)                 = 4
read(8, "llist jobs jobstatus=R jobname=\"\" limit=1000 offset=0", 53) = 53
getcwd("/var/lib/bareos", 4096)         = 16
openat(AT_FDCWD, "/var/log/bareos/bareos-audit.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 79
lseek(79, 0, SEEK_END)                  = 2217541
newfstatat(79, "", {st_mode=S_IFREG|0640, st_size=2217541, ...}, AT_EMPTY_PATH) = 0
write(79, "07-May 11:45 bareos-dir: Console [admin] from [127.0.0.1] cmdline llist jobs jobstatus=R jobname=\"\" limit=1000 offset=0\n", 120) = 120
write(8, "\377\377\377\360", 4)         = 4
getcwd("/var/lib/bareos", 4096)         = 16
getcwd("/var/lib/bareos", 4096)         = 16
getcwd("/var/lib/bareos", 4096)         = 16
geteuid()                               = 130
newfstatat(AT_FDCWD, "/etc/nsswitch.conf", {st_mode=S_IFREG|0644, st_size=1516, ...}, 0) = 0
newfstatat(3, "", {st_mode=S_IFREG|0664, st_size=9253600, ...}, AT_EMPTY_PATH) = 0
newfstatat(3, "", {st_mode=S_IFREG|0664, st_size=9253600, ...}, AT_EMPTY_PATH) = 0
newfstatat(AT_FDCWD, "/proc/self/", {st_mode=S_IFDIR|0555, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
getpid()                                = 1009190
socket(AF_UNIX, SOCK_STREAM, 0)         = 83
fcntl(83, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(83, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
fcntl(83, F_GETFD)                      = 0
fcntl(83, F_SETFD, FD_CLOEXEC)          = 0
connect(83, {sa_family=AF_UNIX, sun_path="/var/lib/sss/pipes/nss"}, 110) = 0
newfstatat(83, "", {st_mode=S_IFSOCK|0777, st_size=0, ...}, AT_EMPTY_PATH) = 0
poll([{fd=83, events=POLLOUT}], 1, 300000) = 1 ([{fd=83, revents=POLLOUT}])
sendto(83, "\24\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0", 16, MSG_NOSIGNAL, NULL, 0) = 16
poll([{fd=83, events=POLLOUT}], 1, 300000) = 1 ([{fd=83, revents=POLLOUT}])
sendto(83, "\1\0\0\0", 4, MSG_NOSIGNAL, NULL, 0) = 4
poll([{fd=83, events=POLLIN}], 1, 300000) = 1 ([{fd=83, revents=POLLIN}])
read(83, "\24\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0", 16) = 16
poll([{fd=83, events=POLLIN}], 1, 300000) = 1 ([{fd=83, revents=POLLIN}])
read(83, "\1\0\0\0", 4)                 = 4
poll([{fd=83, events=POLLOUT}], 1, 300000) = 1 ([{fd=83, revents=POLLOUT}])
sendto(83, "\24\0\0\0\22\0\0\0\0\0\0\0\0\0\0\0", 16, MSG_NOSIGNAL, NULL, 0) = 16
poll([{fd=83, events=POLLOUT}], 1, 300000) = 1 ([{fd=83, revents=POLLOUT}])
sendto(83, "\202\0\0\0", 4, MSG_NOSIGNAL, NULL, 0) = 4
poll([{fd=83, events=POLLIN}], 1, 300000) = 1 ([{fd=83, revents=POLLIN}])
read(83, "\30\0\0\0\22\0\0\0\0\0\0\0\0\0\0\0", 16) = 16
poll([{fd=83, events=POLLIN}], 1, 300000) = 1 ([{fd=83, revents=POLLIN}])
read(83, "\0\0\0\0\0\0\0\0", 8)         = 8
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 84
newfstatat(84, "", {st_mode=S_IFREG|0644, st_size=1785, ...}, AT_EMPTY_PATH) = 0
lseek(84, 0, SEEK_SET)                  = 0
read(84, "root:x:0:0  .................. / redacted /   ..., 4096) = 1785
close(84)                               = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 84
connect(84, {sa_family=AF_UNIX, sun_path="/run/postgresql/.s.PGSQL.5432"}, 110) = 0
................. database comm here ........................................
sendto(84, "X\0\0\0\4", 5, MSG_NOSIGNAL, NULL, 0) = 5
close(84)                               = 0
close(8)                                = 0
close(79)                               = 0
rt_sigprocmask(SIG_BLOCK, ~[RT_1], NULL, 8) = 0
madvise(0x7fea8412a000, 8368128, MADV_DONTNEED) = 0
exit(0)                                 = ?
+++ exited with 0 +++
```
------------ 83 never closed ----------------

**Comment by arogge** [comment] 2024-05-08 13:47
From following the trace I have a guesstimation:
* when bconsole connects, the director will spawn a new threads for the session
* when webui runs the list command, that ua thread will connect to the database
* when initializing libpq, it will do some nss lookup on the passwd service which will in your case will make make nss_sss establish a connection to sssd
* keeping the connection to sssd open is probably a design choice in case you'd do subsequent lookups
* when the bconsole session ends, the thread is destroyed, but as only nss_sss knows about the unix socket connection, there is nothing that cleans this up

Would you please try to reproduce the leak using a bconsole connection and running a successful "list" command in that bconsole?
If my assumptions are correct, each bconsole connection that ran at least one command that accesses the catalog should leak exactly one such unix socket.

If that proves to be true, I'd try to produce a minimal test-case to reproduce the issue and talk to the nss_sss devs to see what we can do.

**Comment by dknight-bg** [comment] 2024-05-08 14:12
The following is observed when running "list" command using bconsole :


After bareos-dir restart :

sudo lsof -p  1143676 | grep type=STREAM
bareos-di 1143676 bareos    1u  unix 0xffff9d5d57ee1100      0t0 3585412057 type=STREAM (CONNECTED)
bareos-di 1143676 bareos    2u  unix 0xffff9d5d57ee1100      0t0 3585412057 type=STREAM (CONNECTED)
bareos-di 1143676 bareos    4u  unix 0xffff9d5d57ee72c0      0t0 3585412064 type=STREAM (CONNECTED)

After bconsole "list" command ( 2 new sockets ) :

sudo lsof -p  1143676 | grep type=STREAM
bareos-di 1143676 bareos    1u  unix 0xffff9d5d57ee1100      0t0 3585412057 type=STREAM (CONNECTED)
bareos-di 1143676 bareos    2u  unix 0xffff9d5d57ee1100      0t0 3585412057 type=STREAM (CONNECTED)
bareos-di 1143676 bareos    4u  unix 0xffff9d5d57ee72c0      0t0 3585412064 type=STREAM (CONNECTED)
bareos-di 1143676 bareos   10u  unix 0xffff9d5d45a45d80      0t0 3585414145 type=STREAM (CONNECTED)
bareos-di 1143676 bareos   11u  unix 0xffff9d5d45a46600      0t0 3585414146 type=STREAM (CONNECTED)


After bconsole exit (1 leaked) :
sudo lsof -p  1143676 | grep type=STREAM
bareos-di 1143676 bareos    1u  unix 0xffff9d5d57ee1100      0t0 3585412057 type=STREAM (CONNECTED)
bareos-di 1143676 bareos    2u  unix 0xffff9d5d57ee1100      0t0 3585412057 type=STREAM (CONNECTED)
bareos-di 1143676 bareos    4u  unix 0xffff9d5d57ee72c0      0t0 3585412064 type=STREAM (CONNECTED)
bareos-di 1143676 bareos   10u  unix 0xffff9d5d45a45d80      0t0 3585414145 type=STREAM (CONNECTED)


----
rpm -qa | grep libpq
libpq5-16.2-42PGDG.rhel9.x86_64

**Comment by arogge** [comment] 2024-05-08 14:47
That confirms my suspicion. 
I'm not sure what the three initial sockets are for, but let's accept them as the baseline.
After the list command, you have two additional sockets, both in the UA thread for the console: one connected to sssd and one connected to postgresql
When bconsole exits, the UA thread is destroyed. During that the connection to postgresql is closed, but the connection to sssd stays open.

**Comment by arogge** [comment] 2024-05-17 11:09
I'm having quite a hard time reproducing your problem.
I set up sssd and the problem simply doesn't happen at all.
```
[pid 40066] write(8, "17-May 11:02 bareos-dir: Console"..., 73) = 73
[pid 40066] getcwd("/var/lib/bareos", 4096) = 16
[pid 40066] getcwd("/var/lib/bareos", 4096) = 16
[pid 40066] getcwd("/var/lib/bareos", 4096) = 16
[pid 40066] getcwd("/var/lib/bareos", 4096) = 16
[pid 40066] fcntl(7, F_GETFL)           = 0x2 (flags O_RDWR)
[pid 40066] fcntl(7, F_SETFL, O_RDWR|O_NONBLOCK) = 0
[pid 40066] write(7, "\27\3\3\0?\\\306\344\327\321\224s\214\301r\346\274ao\266\203BKS\371\377%\352\25\366M\240"..., 68) = 68
[pid 40066] fcntl(7, F_SETFL, O_RDWR)   = 0
[pid 40066] geteuid()                   = 990
[pid 40066] newfstatat(AT_FDCWD, "/etc/nsswitch.conf", {st_mode=S_IFREG|0644, st_size=2124, ...}, 0) = 0
[pid 40066] newfstatat(3, "", {st_mode=S_IFREG|0664, st_size=9253600, ...}, AT_EMPTY_PATH) = 0
[pid 40066] newfstatat(AT_FDCWD, "/var/lib/bareos/.pgpass", 0x7f714fffb4f0, 0) = -1 ENOENT (No such file or directory)
[pid 40066] socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 9
[pid 40066] connect(9, {sa_family=AF_UNIX, sun_path="/run/postgresql/.s.PGSQL.5432"}, 110) = 0
```
As you can see in my testcase Bareos (or rather libpq) doesn't look up anything. It doesn't connect to sssd and it also doesn't look at `/etc/passwd`. It does however try to read `/var/lib/bareos/.pgpass`.
The only odd thing I noticed in your trace is that the `euid()` seems to be 130. Is that the UID of your Bareos user? Is that user in the `/etc/passwd` or is it in a database accessed via sssd?

**Comment by arogge** [comment] 2024-05-28 10:15
I'll close the issue. If you can help me reproduce it, I'm happy to fix it. Just reopen in that case!

**Closed by arogge** 2024-05-28 10:15 UTC
Labels: needs triage, bug
