### ISSUE TITLE
Bareos Webui Restore Ajax core could not load node

### ISSUE THREAD

**Issue by rubinturbo** [bareos/bareos#1823] opened 2024-05-17 08:23 UTC
### Bareos component version

all @23.0.3~pre112.7df7ba8e1-86

### Steps to reproduce

1. Requirement: Backup job with many files and folders
2. Restore over webui
3. just click on the client and wait -> error after ~2 minutes

### Expected results

no error

### Actual results

![restore_issue](https://github.com/bareos/bareos/assets/68944360/b9e070a5-4c15-4324-9116-a7a79f557f27)

in background I check the audit.log:
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline list jobtotals
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline llist jobs last current enabled
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline llist clients current
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline llist backups client="hidden_hostname.fqdn" fileset="any" order=desc limit=1
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline .bvfs_get_jobids jobid=16146 all
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline llist backups client="hidden_hostname.fqdn" fileset="any" order=desc
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline show fileset="hidden_hostname.fqdn"
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline .bvfs_update jobid=15723,13678,13743,13820,13885,13949,14012,14077,14142,14207,14286,14352,14417,14481,14547,14613,14680,14762,14829,14895,14960,15028,15096,15164,15246,15314,15381,15447,15516,15584,15652,15735,15803,15870,15937,16006,16075,16146
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline llist clients current
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline show client=hidden_hostname.fqdn
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline .bvfs_get_jobids jobid=16146 all
17-Mai 09:56 bareos-dir: Console [admin] from [::1] cmdline .bvfs_lsdirs jobid=15723,13678,13743,13820,13885,13949,14012,14077,14142,14207,14286,14352,14417,14481,14547,14613,14680,14762,14829,14895,14960,15028,15096,15164,15246,15314,15381,15447,15516,15584,15652,15735,15803,15870,15937,16006,16075,16146 path= limit=1000 offset=0
17-Mai 09:58 bareos-dir: Console [admin] from [::1] cmdline .bvfs_lsfiles jobid=15723,13678,13743,13820,13885,13949,14012,14077,14142,14207,14286,14352,14417,14481,14547,14613,14680,14762,14829,14895,14960,15028,15096,15164,15246,15314,15381,15447,15516,15584,15652,15735,15803,15870,15937,16006,16075,16146 path= limit=1000 offset=0
17-Mai 09:58 bareos-dir: Console [admin] from [::1] cmdline .bvfs_lsfiles jobid=15723,13678,13743,13820,13885,13949,14012,14077,14142,14207,14286,14352,14417,14481,14547,14613,14680,14762,14829,14895,14960,15028,15096,15164,15246,15314,15381,15447,15516,15584,15652,15735,15803,15870,15937,16006,16075,16146 path=@ limit=1000 offset=0

### Environment

```markdown
- OS: ``
- component:
```

### Relevant log output

```shell
I also check the audit commands at the bconsole... there are no Errors:

*.bvfs_get_jobids jobid=16146 all
15723,13678,13743,13820,13885,13949,14012,14077,14142,14207,14286,14352,14417,14481,14547,14613,14680,14762,14829,14895,14960,15028,15096,15164,15246,15314,15381,15447,15516,15584,15652,15735,15803,15870,15937,16006,16075,16146
*.bvfs_lsdirs jobid=15723,13678,13743,13820,13885,13949,14012,14077,14142,14207,14286,14352,14417,14481,14547,14613,14680,14762,14829,14895,14960,15028,15096,15164,15246,15314,15381,15447,15516,15584,15652,15735,15803,15870,15937,16006,16075,16146 path= limit=1000 offset=0
99	0	0	A A A A A A A A A A A A A A	.
98	0	0	A A A A A A A A A A A A A A	/
*.bvfs_lsfiles jobid=15723,13678,13743,13820,13885,13949,14012,14077,14142,14207,14286,14352,14417,14481,14547,14613,14680,14762,14829,14895,14960,15028,15096,15164,15246,15314,15381,15447,15516,15584,15652,15735,15803,15870,15937,16006,16075,16146 path= limit=1000 offset=0
*.bvfs_lsfiles jobid=15723,13678,13743,13820,13885,13949,14012,14077,14142,14207,14286,14352,14417,14481,14547,14613,14680,14762,14829,14895,14960,15028,15096,15164,15246,15314,15381,15447,15516,15584,15652,15735,15803,15870,15937,16006,16075,16146 path=@ limit=1000 offset=0
*

I still set the option in /etc/bareos-webui/configuration.ini :
~~~
[restore]
; Restore filetree refresh timeout in milliseconds
; Default:
;filetree_refresh_timeout=120000
filetree_refresh_timeout=500000
~~~
```

### Anything else?

What can I do the prevent the error in the webui? Special apache-settings?
apache2 with 2.4.59-1~deb11u1 is running

Thanks Ralf!

**Comment by arogge** [comment] 2024-06-04 10:35
Hi,
could you try to reproduce the problem with the web developer tab opened on "network" and see what the response for the failed query is?
I'd be interested in the response-headers, but the response-body might be helpful, too. Maybe you're running into Apache HTTPd's ProxyTimeout (which you cannot configure in the WebUI's ini-files).

**Comment by ra-schu** [comment] 2024-06-18 12:23
Hi arogge,

thanks for the reply.

"""
Time: 112727 ms

The  response-headers from "https://bareoshost/restore/filebrowser?jobid=18427&client=bareosclient&mergefilesets=1&mergejobs=1&limit=2000&id=%23" is:

HTTP/1.1 200 OK
Date: Tue, 18 Jun 2024 11:56:10 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Length: 31
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive
Content-Type: application/json

The  response from "https://bareoshost/restore/filebrowser?jobid=18427&client=bareosclient&mergefilesets=1&mergejobs=1&limit=2000&id=%23" is:

Decoding failed: Syntax error[]
"""

I also think it could be a timeout.
We use Apache2 with Debian 11.

Where could I look for timeouts?

I've already tried /etc/apache2/apache2.conf with 'Timeout 180'.

Thank you Ralf

**Comment by rubinturbo** [comment] 2024-07-08 11:01
@arogge/Adreas: Do you have any other ideas where I could look because of the timeout? Thanks Ralf

('ra-schu' is my other account)

**Comment by arogge** [comment] 2024-07-08 11:50
But you're getting a "200 OK" response, which means at least on the HTTP side everything seeems to be happy.
However, the script seems to have outputted only `Decoding failed: Syntax error[]` which to me looks like some error message followed by an empty JSON array.
If I'm not mistaken that error comes from the Zend framework itself. It seems to indicate a JSON parsing error.

The WebUI does a bconsole call that is supposed to return JSON. It seems like in this case the JSON returned by the Bareos director to the WebUI is ill-formed.
Can you check in bareos-audit.log what command is run on the director and see if that produces parseable JSON output (you might have to switch to the JSON API first when testing using `.api 2`)?

**Comment by pstorz** [comment] 2024-08-08 09:24
As we got no answer since one month I am closing the issue now.

**Closed by pstorz** 2024-08-08 09:24 UTC
Labels: needs triage, bug
