### ISSUE TITLE
[Bareos 23.0.2] Using bscan on a volume created by a Virtual Full job no files are recognized on it

### ISSUE THREAD

**Issue by Vemerspa** [bareos/bareos#1855] opened 2024-06-12 14:44 UTC
### Bareos component version

1. bareos-dir version : 23.0.2~pre42.73384cd07
2. bareos-sd version : 23.0.2~pre42.73384cd07
3. bareos-fd version : 23.0.2~pre42.73384cd07

### Steps to reproduce

1 - Create a volume with a Virtual Full job.
2 - Such volume is stored in Bareos as a single file.
3 - Try to restore the file list (present on the volume) on the catalog (or just try to list the content of the volume) using the command bscan .

### Expected results

In previous version 16.0 I was always able to scan and restore the file list present on a volume created by a Virtual Full job to the catalog using the program  bscan .

If I use the  bscan  command with a volume created by a normal Full (or Differential, or Incremental) job I'm able to list and restore on the catalog all the files present on it.
So the same must happens with a volume created by a Virtual Full job.

### Actual results

Now instead no files are recognized in the volume (created by a Virtual Full job) by the  bscan  command.
But :
- if I use the command  bls  on the same volume I can correctly list all the files and directory contained in it;
- if I use the command  bextract  on the same volume I can correctly extract all the files and directory contained in it.

### Environment

```markdown
- OS: Rocky Linux 9.3
- component:
```

**Comment by arogge** [comment] 2024-06-12 14:48
Can you actually reproduce this in a minimal reproducible setup?

We know that there are cases where the virtual full is missing the start of session and/or end of session records, which is required to make `bscan` work correctly. We are just unable to reliably reproduce the issue which makes it next to impossible to fix it.

So long story short: if you can tell us how to reproduce this we can probably fix it.

**Comment by sebsura** [comment] 2024-06-13 04:53
Could you run `bscan` with `-r/--list-records` and post the result here ?
Then we could check if the SOS record is indeed missing or not.

**Comment by Vemerspa** [comment] 2024-06-13 06:34
The result of  bscan -r  of the volume is in the file attached (compressed).
[bscan-results.txt.tar.gz](https://github.com/user-attachments/files/15814890/bscan-results.txt.tar.gz)

**Comment by sebsura** [comment] 2024-06-13 06:48
Looks like the SOS record is indeed missing. (There is no record with FileIndex = -4).  We recently pushed a fix for this which is in 23.0.3.
This fix only applies to _new_ virtual fulls which are not based on a virtual full created without the fix.  Let us know if you can still reproduce this issue on 23.0.3+.

**Comment by SamuelBoerlin** [comment] 2024-06-13 08:04
Since always-incremental uses virtual full too for consolidation, does that mean we have to run regular full backups once to ensure we don't possibly run into this issue in the future?

**Comment by sebsura** [comment] 2024-06-13 11:10
This is only a problem if you need to use bscan.  Especially when using always-incremental, you should not rely on bscan since it will not record the jobs in the right order!

But yes, you can (hopefully) avoid this particular problem by running a new full.

**Comment by Vemerspa** [comment] 2024-06-13 13:40
> Looks like the SOS record is indeed missing. (There is no record with FileIndex = -4). We recently pushed a fix for this which is in 23.0.3. This fix only applies to _new_ virtual fulls which are not based on a virtual full created without the fix. Let us know if you can still reproduce this issue on 23.0.3+.

Hello I have updated Bareos with the last version (23.0.4), and then I have executed a new Virtual Full job.
Then I have tried the command bscan on such new volume :
- now the scan is correct and all the files have been found !

The issue which I reported can be considered resolved.

Thanks

**Comment by sebsura** [comment] 2024-06-14 07:09
Ill close this issue then.  Feel free to reopen it if you run into the same problem again!

**Closed by sebsura** 2024-06-14 07:09 UTC
Labels: bug
