### ISSUE TITLE
Cannot build RPM on RHEL 8 using included bareos-Release-23.0.2/core/platforms/packaging/bareos.spec file

### ISSUE THREAD

**Issue by RiotNrrrd** [bareos/bareos#1822] opened 2024-05-17 07:13 UTC
### Bareos component version

23.0.2

### Steps to reproduce

1. Copy the file _bareos-Release-23.0.2/core/platforms/packaging/bareos.spec_ from the _23.0.2.tar.gz_ bundle to _~/rpmbuild/SPECS/bareos.spec_ on a RHEL 8 system.

2. cd _~/rpmbuild/SPECS_
3. Edit _bareos.spec_, change _Version:_ from "_0_" to "_23.0.2_", change _Release:_ from "_0_" to "_1%{?dist}_".
4. Run _rpmbuild -bb bareos.spec_

### Expected results

Expect the RPMs to build, or at least get past this error.

### Actual results

Build dies with

`+ install -d -m 755 /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/usr/lib/systemd/system`
`+ install -m 644 cmake-build/core/platforms/systemd/bareos-dir.service /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/usr/lib/systemd/system`
`install: cannot stat 'cmake-build/core/platforms/systemd/bareos-dir.service': No such file or directory`
`error: Bad exit status from /var/tmp/rpm-tmp.1Cq7Ay (%install)`

### Environment

```markdown
- OS: `Red Hat Enterprise Linux release 8.9 (Ootpa)`
- component: rpmbuild
```

### Relevant log output

```shell
[root@bareos SPECS]# rpmbuild -bb bareos.spec

[...]

+ install -d -m 755 /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/usr/lib/systemd/system
+ install -m 644 cmake-build/core/platforms/systemd/bareos-dir.service /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/usr/lib/systemd/system
install: cannot stat 'cmake-build/core/platforms/systemd/bareos-dir.service': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.1Cq7Ay (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.1Cq7Ay (%install)
```

### Anything else?

Earlier upstream in the build, the 3 _bareos-*.service_ files had already been installed by _something_ under _BUILD/bareos/cmake-build_:

`[...]`
`Install the project...`
`/usr/bin/cmake -P cmake_install.cmake`
`-- Install configuration: ""`
`-- Installing: /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/var/log/bareos`
`-- Installing: /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/var/lib/bareos`
`-- Installing: /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/etc/rc.d/init.d/bareos-fd`
`-- Installing: /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/etc/rc.d/init.d/bareos-sd`
`-- Installing: /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/etc/rc.d/init.d/bareos-dir`
`-- Installing: /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/usr/lib/systemd/system/bareos-sd.service`
`-- Installing: /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/usr/lib/systemd/system/bareos-fd.service`
`-- Installing: /root/rpmbuild/BUILDROOT/bareos-23.0.2-1.el8.x86_64/usr/lib/systemd/system/bareos-dir.service`

so I don't really understand why these _CMAKE_BUILDDIR_ lines in the _.spec_ file are getting run (and the first fails):

`[root@bareos SPECS]# sed -n '1021,1026p' bareos.spec`
`# install systemd service files`
`%if 0%{?systemd_support}`
`install -d -m 755 %{buildroot}%{_unitdir}`
`install -m 644 %{CMAKE_BUILDDIR}/core/platforms/systemd/bareos-dir.service %{buildroot}%{_unitdir}`
`install -m 644 %{CMAKE_BUILDDIR}/core/platforms/systemd/bareos-fd.service %{buildroot}%{_unitdir}`
`install -m 644 %{CMAKE_BUILDDIR}/core/platforms/systemd/bareos-sd.service %{buildroot}%{_unitdir}`

**Comment by arogge** [comment] 2024-05-17 08:49
We're building with that spec-file in continous integration all the time. However, the additional install looks redundant, maybe you can just remove that section?

Other than that, could you try building from the bareos-23 branch with the following steps and see if that fails for you, too?
```
git clone https://github.com/bareos/bareos.git
cd bareos
git checkout bareos-23
devtools/build-rpm.sh --nocheck
```

**Comment by RiotNrrrd** [comment] 2024-05-24 04:18
@arogge Hi Andreas, sorry for the delayed response.

I thought what you thought and commented out those 4 lines; unfortunately that just gave me different errors.  :-(

I have not had time to try your request to build from the bareos-23 branch yet.  I just wanted to add that shortly after I posted this issue, I went back and did an RPM build of Bareos 22.1.4 from the source tarball and the included _.spec_ file it came with (with 2 minor edits) and it worked fine.  So something seems to have changed in the 23 release lineage that broke it.

**Comment by arogge** [comment] 2024-05-24 08:40
I can assure you that every set of Bareos RPMs we publish is built using the `core/platforms/packaging/bareos.spec` from the source-tree.

I tried the follwing process:
```console
[user@host ~]$ SRCDIR="$(rpm --eval '%{_sourcedir}')"
[user@host ~]$ mkdir -p "$SRCDIR"
[user@host ~]$ curl -L https://github.com/bareos/bareos/archive/refs/tags/Release/23.0.2.tar.gz >"$SRCDIR/bareos-23.0.2.tar.gz"
[user@host ~]$ tar xzfO "$SRCDIR/bareos-23.0.2.tar.gz" '**/core/platforms/packaging/bareos.spec' > bareos.spec
[user@host ~]$ rpmdev-bumpspec --new="23.0.2-1%{?dist}" bareos.spec
[user@host ~]$ rpmbuild -bb --nocheck bareos.spec
```
And it worked just like I expected.

To rule out that it just accidentially works on our CI and my machine I tried with a fresh RHEL8 container:
```console
[user@host ~]$ podman run --rm -it registry.redhat.io/ubi8/ubi
[root@container /]$ dnf install rpm-build rpmdevtools
[root@container /]$ useradd build
[root@container /]$ su - build
[build@container /]$ rpmdev-setuptree
(follow steps outlined above with the build failing due to missing buildrequires)
# disable glusterfs as devel-packages are next to unobtainable for RHEL
[build@container ~]$ sed -e '/%define glusterfs 1/d' -i bareos.spec
[build@container /]$ exit
[root@container /]$ dnf install -y <all-the-packages-rpmbuild-reported-missing>
[root@container /]$ su - build
[build@container ~]$ rpmbuild -bb --nocheck bareos.spec
```
That errored out because it didn't build droplet while rpm wanted to package it. The problem here is missing BuildRequires for `libxml2-devel` and `json-c-devel`. After installing these two packages, the build works fine.

So if you want, you can open a PR to add the missing BuildRequires. Besides that I'm pretty sure the SPECfile is working fine (even though there is a lot of room for improvement left).

**Comment by arogge** [comment] 2024-06-04 10:37
If I understand correctly, the issue is solved. I'll close it.

**Closed by arogge** 2024-06-04 10:37 UTC
Labels: needs triage, bug

**Comment by RiotNrrrd** [comment] 2024-06-04 10:42
Hi Andreas,

I had not yet had a chance to test your suggestion.  Not sure why you say it is solved unless some update to the .spec file has been recently made. I apologize for the delay in responding/testing your suggestion.

**Comment by arogge** [comment] 2024-06-04 12:56
The response I got was your :+1: to my comment. Feel free to reopen if you can reproduce the issue in a clean build environment.
